include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_single_quotes: error
    avoid_print: error
    avoid_multiple_declarations_per_line: error
    avoid_returning_null: warning
    avoid_returning_null_for_future: warning
    avoid_returning_null_for_void: warning
    unnecessary_new: error

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: true
    avoid_multiple_declarations_per_line: true
    avoid_returning_null: true
    avoid_returning_null_for_future: true
    avoid_returning_null_for_void: true
    unnecessary_new: true

