name: smart_translation
description: Package used to translate
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  smart_common_shared:
    path: C:\git\smartmaint\SmartMaintUI\smart_manufacturing_modular\packages\smart_common_shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: